services:
  redis:
    image: redis:alpine

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
      target: nodejs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development